version: "3.9"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kmProFitness
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build: .
    depends_on:
      - mysql
    environment:
      - MYSQL_URL=mysql://root:root@mysql:3306/kmProFitness
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
